// <auto-generated />
using BasicAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicAPI.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20230717223905_InitialPersonContextCommit")]
    partial class InitialPersonContextCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("BasicAPI.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            FirstName = "Billy",
                            LastName = "Jean",
                            Profession = "Singer"
                        },
                        new
                        {
                            Id = 2,
                            Age = 58,
                            FirstName = "John",
                            LastName = "Madden",
                            Profession = "Broadcaster"
                        },
                        new
                        {
                            Id = 3,
                            Age = 16,
                            FirstName = "John",
                            LastName = "Smith",
                            Profession = "Programmer"
                        },
                        new
                        {
                            Id = 4,
                            Age = 12,
                            FirstName = "Nicholas",
                            LastName = "Bolde",
                            Profession = "Thief"
                        },
                        new
                        {
                            Id = 5,
                            Age = 45,
                            FirstName = "Mark",
                            LastName = "Lawrence",
                            Profession = "Writer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
